language: c
env:
 - CABALVER=1.22 GHCVER=7.6.3
 - CABALVER=1.22 GHCVER=7.8.4
 - CABALVER=1.22 GHCVER=7.10.1
 - CABALVER=1.22 GHCVER=head

matrix:
  allow_failures:
   - env: CABALVER=1.22 GHCVER=7.10.1
   - env: CABALVER=1.22 GHCVER=head
    
before_install:
 - travis_retry sudo add-apt-repository -y ppa:hvr/ghc 
 - travis_retry sudo apt-get update

 - sudo apt-cache search build-essential libevent-dev
 - wget https://www.torproject.org/dist/tor-0.2.7.1-alpha.tar.gz
 - tar -xzf tor-0.2.7.1-alpha.tar.gz
 - cd tor-0.2.7.1-alpha/
 - ./configure --disable-unittests --disable-system-torrc
 - make -j4
 - sudo make install
 - cd ..

# Configure & launch tor service
 - echo "RunAsDaemon 1" >> ~/.torrc
 - echo "ControlPort 9051" >> ~/.torrc
 - echo "CookieAuthentication 1" >> ~/.torrc
 - echo "ExtORPortCookieAuthFileGroupReadable 1" >> ~/.torrc
 - tor 

# Wait until Tor control port is open
 - nc -zvv localhost 9051; out=$?; while [[ $out -ne 0 ]]; do echo "Retry hit port 9051..."; nc -zvv localhost 9051; out=$?; sleep 1; done

# Installing cabal and ghc
 - travis_retry sudo apt-get install cabal-install-$CABALVER ghc-$GHCVER # see note about happy/alex
 - export PATH=$HOME/.cabal/bin:/opt/ghc/$GHCVER/bin:/opt/cabal/$CABALVER/bin:$PATH
 - travis_retry cabal update

# Happy/alex hack for ghc > 7.8.1
 - |
   if [ $GHCVER = "head" ] || [ ${GHCVER%.*} = "7.8" ] || [ ${GHCVER%.*} = "7.10" ]; then
     travis_retry sudo apt-get install happy-1.19.4 alex-3.1.3
     export PATH=/opt/alex/3.1.3/bin:/opt/happy/1.19.4/bin:$PATH
   else
     travis_retry sudo apt-get install happy alex
   fi

# Install hlint (via apt-get if available, otherwise via cabal)
 - travis_retry sudo apt-get -q -y install hlint || cabal install hlint
 
# Install hpc-coveralls
 - cabal install hpc-coveralls -j --bindir=$HOME/.cabal/bin/ --constraint='aeson >= 0.7'
 - which run-cabal-test


install:
 - cabal --version
 - echo "$(ghc --version) [$(ghc --print-project-git-commit-id 2> /dev/null || echo '?')]"
 - travis_retry cabal install --only-dependencies --enable-tests --enable-benchmarks -j

script:
 # Test reading of tor auth cookie
 - sudo -E su $USER -c 'cat /var/run/tor/control.authcookie'

 - hlint src --ignore="Parse error"
 - cabal configure --enable-tests --enable-benchmarks --enable-coverage -fdebug 
 - cabal build -j
 - travis_retry sudo -E su $USER -c '/home/$USER/.cabal/bin/run-cabal-test --cabal-name=cabal --show-details=streaming'
 - cabal check
 - cabal sdist
 
# The following scriptlet checks that the resulting source distribution can be built & installed
 - export SRC_TGZ=$(cabal info . | awk '{print $2 ".tar.gz";exit}') ;
   cd dist/;
   if [ -f "$SRC_TGZ" ]; then
      cabal install --force-reinstalls "$SRC_TGZ";
   else
      echo "expected '$SRC_TGZ' not found";
      exit 1;
   fi ;
   cd ../

after_script:
 - find .
 - hpc-coveralls test-suite --exclude-dir=test --display-report
